Documentation:
    Enabled: false
Metrics/LineLength:
  Max: 120
AllCops:
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
Style/SignalException:
  EnforcedStyle: semantic
