redis:
  image: redis
  ports:
    - "6379:6379"

db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"
  volumes:
    - ./backups:/backups

web:
  build: .
  command: ./web.sh
  ports:
    - "8082:8082"
  links:
    - db
    - redis
  volumes:
    - .:/myapp
  env_file: .env.web

web_clone:
  build: .
  command: ./web_clone.sh
  ports:
    - "8083:8083"
  links:
    - db
    - redis
  volumes:
    - .:/myapp
  env_file: .env.web
  environment:
    PORT: 8083

worker:
  build: .
  command: ./worker.sh
  links:
    - db
    - redis
  volumes:
    - .:/myapp
  env_file: .env.web
